openapi: "3.0.0"

info:
  title: Administration Produit
  version: "1.0.0"
  description: Produit part of Adminstration app API

servers:
  - url: http://localhost:8080/

tags:
  - name: Produit
    description: produit specific data.
paths:
  /produit:
    get:
      tags:
        - Produit
        - Gets
      summary: Get All Produit
      operationId: getProduit
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                type: array  # Return a list of AppRoleDto
                items:
                  $ref: '../model/produit/ProduitResp.yml'
        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST
    post:
      tags:
        - Produit
        - Posts
      summary: Create a Produit
      operationId: createProduit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/produit/ProduitRequest.yml'
            example:
              libelle: "Sac De Riz"
              qtStock: 60000
              appUserId: 1
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                type: array  # Return a list of AppRoleDto
                items:
                  $ref: '../model/produit/ProduitResp.yml'
        '400':
          description: BAD REQUEST
  /produit-reference:
    get:
      tags:
        - Produit
        - Gets
        - WithReferences
      summary: find One By id
      operationId: getAppProduitById
      responses:
        200:
          description: SUCCESS
          content:
            'application/json':
              schema:
                $ref: '../model/produit/ProduitResp.yml'
    put:
      tags:
        - Produit
        - Puts
        - WithReferences
      summary: Update a Produit
      operationId: updateProduit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/produit/ProduitRequest.yml'
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                type: array  # Return a list of AppRoleDto
                items:
                  $ref: '../model/produit/ProduitResp.yml'
        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST
    delete:
      tags:
        - Produit
        - Deletes
        - WithReferences
      summary: Delete a Produit
      operationId: deleteProduit
      responses:
        '200':
          description: SUCCESS
        '204':
          description: No Content
        '404':
          description: NOT FOUND